services:
  - type: web
    name: vibe-talk-backend-yash
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn vibe_talk.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: vibe-talk-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: vibe-talk-db
    databaseName: vibedb
    user: vibeuser
    plan: free
